language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g standard
  - npm i -g mocha
install:
  - travis_retry npm install
script:
  - npm test